version: 2

run:
  timeout: 3m
  tests: true
issues:
  exclude-use-default: false
  exclude-dirs:
    - tmp
    - vendor

linters:
  enable:
    - govet
    - staticcheck
    - ineffassign
    - errcheck
