version: 2

run:
  timeout: 3m
  tests: true
  skip-dirs:
    - tmp
    - vendor

issues:
  exclude-use-default: false

linters:
  enable:
    - govet
    - staticcheck
    - ineffassign
    - errcheck

linters-settings:
  govet:
    check-shadowing: true
